// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8e01779d-1b01-4697-9f83-ed1799856764",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_nLRb1kvsZ",
    "aws_user_pools_web_client_id": "7icep5kkt8fou4nk52ft2gea48",
    "oauth": {}
};


export default awsmobile;
